/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/DnullP/se_work/router"
	"github.com/DnullP/se_work/utils"
)

func init() {

}

func main() {
	utils.InitDB()

	log.Printf("Server started")

	router := router.NewRouter()

	log.Fatal(router.Run(":8080"))
}
