/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package response

type Bill struct {
	CheckInTime  string  `json:"check_in_time"`
	CheckOutTime string  `json:"check_out_time"`
	RoomID       int64   `json:"room_id"`
	TotalCost    float64 `json:"total_cost"`
}
