/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package response

type DeviceStatus_room_id struct {
	DeviceStatus
	RoomID uint `json:"room_id"`
}

type DeviceStatusList struct {
	DeviceList []DeviceStatus_room_id `json:"device_list"`
}
