/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package response

type Report struct {
	RoomList []RoomList `json:"room_list"`
}

type RoomList struct {
	BillTimes       int64   `json:"bill_times"`
	DailyCost       float64 `json:"daily_cost"`
	RoomID          int64   `json:"room_id"`
	SchedTimes      int64   `json:"sched_times"`
	TurnTimes       int64   `json:"turn_times"`
	TweatSpeedTimes int64   `json:"tweat_speed_times"`
	TweatTemTimes   int64   `json:"tweat_tem_times"`
	// this is the running time, not times !!!
	WorkingTime float64 `json:"working_time"`
}
