/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package response

type DeviceStatus struct {

	Working string `json:"working"`

	Mode string `json:"mode"`

	// a float
	EnvTemperature string `json:"env_temperature"`

	// a float
	TargetTemperature string `json:"target_temperature"`

	// a float
	Speed string `json:"speed"`

	// a float
	TotalCost string `json:"total_cost"`
}
