/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package response

type Report struct {

	RoomId string `json:"room_id"`

	TurnTimes string `json:"turn_times"`

	SchedTimes string `json:"sched_times"`

	BillTimes string `json:"bill_times"`

	TweatTemTimes string `json:"tweat_tem_times"`

	TweatSpeedTimes string `json:"tweat_speed_times"`

	// this is the running time, not times !!!
	WorkingTime string `json:"working_time"`

	DailyCost string `json:"daily_cost"`
}
