/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controller

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// BillCostGet - bill_cost
func BillCostGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// BillDetailGet - bill_detail
func BillDetailGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
