/*
 * air_condition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package controller

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AdminControlPost - admin_control
func AdminControlPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllDeviceStatusGet - get_all_device_status
func GetAllDeviceStatusGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDeviceStatusGet - get_device_status
func GetDeviceStatusGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
